// @ts-nocheck
"use client";
import { useRef, useState } from "react";
type Key="source"|"style"|"cutout"|"logo"|"plate";
const uploadItems=[{key:"source" as Key,label:"原始人車照",required:true},{key:"style" as Key,label:"參考海報"},{key:"cutout" as Key,label:"去背人車 PNG"},{key:"logo" as Key,label:"Logo PNG"},{key:"plate" as Key,label:"車牌 PNG"}];
function loadImage(url:string){return new Promise<HTMLImageElement>((res,rej)=>{const img=new Image();img.crossOrigin="anonymous";img.onload=()=>res(img);img.onerror=rej;img.src=url;});}
async function compressImage(file:File,maxSize=1400,quality=.78){const img=document.createElement("img");const url=URL.createObjectURL(file);await new Promise<void>((res,rej)=>{img.onload=()=>res();img.onerror=()=>rej();img.src=url});const scale=Math.min(1,maxSize/Math.max(img.width,img.height));const w=Math.round(img.width*scale),h=Math.round(img.height*scale);const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d")!.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);const blob=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(),"image/jpeg",quality));return new File([blob],file.name.replace(/\.[^.]+$/,".jpg"),{type:"image/jpeg"});}
export default function Home(){
const inputRefs=useRef<Partial<Record<Key,HTMLInputElement|null>>>({}); const canvasRef=useRef<HTMLCanvasElement|null>(null);
const [files,setFiles]=useState<Partial<Record<Key,File>>>({}); const [urls,setUrls]=useState<Partial<Record<Key,string>>>({}); const [cutoutUrl,setCutoutUrl]=useState(""); const [backgroundUrl,setBackgroundUrl]=useState(""); const [loading,setLoading]=useState(false);
const [status,setStatus]=useState("v23：穩定排版版。沒有去背 PNG 時，自動用照片框模式，版面不亂跑。");
const [carModel,setCarModel]=useState("2025 NISSAN X-TRAIL 1.5T"); const [headline,setHeadline]=useState("新貨到"); const [jpText,setJpText]=useState("新入荷しました"); const [feature,setFeature]=useState("超值 / 輕油電 / 現省大價差"); const [price,setPrice]=useState("75.9");
const [mode,setMode]=useState("photo"); const [useLocalBg,setUseLocalBg]=useState(true); const [subjectX,setSubjectX]=useState("-90"); const [subjectY,setSubjectY]=useState("300"); const [subjectW,setSubjectW]=useState("1760"); const [photoY,setPhotoY]=useState("285"); const [photoH,setPhotoH]=useState("560"); const [barY,setBarY]=useState("900"); const [priceX,setPriceX]=useState("1060"); const [priceY,setPriceY]=useState("215");
function pick(key:Key,file?:File){if(!file)return;const url=URL.createObjectURL(file);setFiles(p=>({...p,[key]:file}));setUrls(p=>({...p,[key]:url}));if(key==="cutout")setMode("cutout");setStatus(`已上傳：${uploadItems.find(x=>x.key===key)?.label}`);}
function makeLocalBackground(){const c=document.createElement("canvas"),W=1600,H=1200;c.width=W;c.height=H;const ctx=c.getContext("2d")!;const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,"#030303");bg.addColorStop(.28,"#171717");bg.addColorStop(.58,"#070707");bg.addColorStop(1,"#260000");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(let i=0;i<42;i++){const y=110+i*23,g=ctx.createLinearGradient(-160,y,W+180,y-210);g.addColorStop(0,"rgba(255,0,0,0)");g.addColorStop(.22,i%4===0?"rgba(255,25,0,.96)":"rgba(255,110,0,.34)");g.addColorStop(.7,i%4===0?"rgba(255,170,45,.66)":"rgba(255,50,0,.20)");g.addColorStop(1,"rgba(255,0,0,0)");ctx.strokeStyle=g;ctx.lineWidth=i%4===0?11:4;ctx.beginPath();ctx.moveTo(-240,y+88);ctx.lineTo(W+280,y-165);ctx.stroke()}const floor=ctx.createLinearGradient(0,560,0,H);floor.addColorStop(0,"rgba(55,55,55,.28)");floor.addColorStop(.42,"rgba(15,15,15,.96)");floor.addColorStop(1,"rgba(0,0,0,1)");ctx.fillStyle=floor;ctx.fillRect(0,560,W,640);for(let i=0;i<5;i++){const fog=ctx.createRadialGradient(170+i*310,760+i*18,0,170+i*310,760+i*18,520);fog.addColorStop(0,`rgba(255,255,255,${.11-i*.012})`);fog.addColorStop(.55,`rgba(255,135,45,${.04-i*.004})`);fog.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=fog;ctx.fillRect(0,430,W,650)}const v=ctx.createRadialGradient(W/2,H/2,260,W/2,H/2,960);v.addColorStop(0,"rgba(0,0,0,0)");v.addColorStop(1,"rgba(0,0,0,.82)");ctx.fillStyle=v;ctx.fillRect(0,0,W,H);return c.toDataURL("image/png");}
async function generateBackground(){if(useLocalBg||!files.style){const local=makeLocalBackground();setBackgroundUrl(local);return local}try{const form=new FormData();form.append("style",await compressImage(files.style,1200,.72));form.append("prompt","只生成空的黑紅工業 showroom 背景，不要生成車、人、中文字、Logo、價格牌。");const res=await fetch("/api/generate-background",{method:"POST",body:form});const data=await res.json();if(res.ok&&data.imageUrl){setBackgroundUrl(data.imageUrl);return data.imageUrl}}catch{}const local=makeLocalBackground();setBackgroundUrl(local);return local}
async function getSubjectOrSource(){if(urls.cutout){setCutoutUrl(urls.cutout);return urls.cutout}if(!urls.source)throw new Error("請先上傳原始人車照。");setCutoutUrl(urls.source);return urls.source}
function drawMetalText(ctx:any,text:string,x:number,y:number){ctx.save();ctx.font="900 182px Microsoft JhengHei, Arial Black";ctx.lineJoin="round";ctx.shadowColor="rgba(0,0,0,.92)";ctx.shadowBlur=42;ctx.shadowOffsetX=14;ctx.shadowOffsetY=16;ctx.lineWidth=32;ctx.strokeStyle="#050505";ctx.strokeText(text,x+8,y+12);const g=ctx.createLinearGradient(0,y-150,0,y+40);g.addColorStop(0,"#fff");g.addColorStop(.18,"#a8a8a8");g.addColorStop(.38,"#3f3f3f");g.addColorStop(.55,"#f7f7f7");g.addColorStop(.78,"#6c6c6c");g.addColorStop(1,"#fff");ctx.shadowBlur=0;ctx.fillStyle=g;ctx.fillText(text,x,y);ctx.lineWidth=3;ctx.strokeStyle="rgba(255,255,255,.8)";ctx.strokeText(text,x,y);ctx.restore()}
function drawTop(ctx:any){ctx.save();ctx.font="900 78px Microsoft JhengHei, Arial Black";ctx.fillStyle="#e60012";ctx.shadowColor="rgba(0,0,0,.95)";ctx.shadowBlur=12;ctx.fillText(jpText,58,118);ctx.restore();ctx.save();ctx.translate(58,158);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(755,0);ctx.lineTo(708,80);ctx.lineTo(-30,80);ctx.closePath();ctx.fillStyle="#f7f7f7";ctx.fill();ctx.font="900 43px Microsoft JhengHei, Arial";ctx.fillStyle="#070707";ctx.fillText(feature,26,54);ctx.restore();drawMetalText(ctx,headline,625,172)}
function drawPrice(ctx:any){const x=Number(priceX)||1060,y=Number(priceY)||215,w=455,h=260;ctx.save();ctx.translate(x,y);ctx.rotate(-.065);ctx.shadowColor="rgba(0,0,0,.82)";ctx.shadowBlur=26;ctx.shadowOffsetX=15;ctx.shadowOffsetY=17;const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,"#ffe46e");bg.addColorStop(.45,"#d49d32");bg.addColorStop(1,"#8f4f00");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.shadowBlur=0;ctx.strokeStyle="#150700";ctx.lineWidth=12;ctx.strokeRect(0,0,w,h);ctx.globalAlpha=.92;ctx.fillStyle="#ffd44c";ctx.fillRect(18,16,w-36,h-32);ctx.globalAlpha=1;ctx.font="900 61px Microsoft JhengHei";ctx.fillStyle="#111";ctx.fillText("真的就賣！",34,74);ctx.font="900 148px Arial Black";ctx.lineWidth=9;ctx.strokeStyle="#fff";ctx.strokeText(price,26,204);ctx.fillStyle="#e60012";ctx.fillText(price,26,204);ctx.font="900 50px Microsoft JhengHei";ctx.fillText("萬",348,194);ctx.restore()}
function drawPhoto(ctx:any,img:any){const x=82,y=Number(photoY)||285,w=1235,h=Number(photoH)||560;ctx.save();ctx.shadowColor="rgba(0,0,0,.75)";ctx.shadowBlur=22;ctx.shadowOffsetX=10;ctx.shadowOffsetY=14;ctx.fillStyle="#111";ctx.fillRect(x-6,y-6,w+12,h+12);ctx.restore();const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s,sx=Math.max(0,(img.width-sw)/2),sy=Math.max(0,(img.height-sh)/2);ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);const shade=ctx.createLinearGradient(0,y+h-180,0,y+h);shade.addColorStop(0,"rgba(0,0,0,0)");shade.addColorStop(1,"rgba(0,0,0,.42)");ctx.fillStyle=shade;ctx.fillRect(x,y+h-180,w,180)}
function drawCutout(ctx:any,img:any){const tw=Number(subjectW)||1760,th=tw*(img.height/img.width),x=Number(subjectX)||-90,y=Number(subjectY)||300;ctx.save();ctx.globalAlpha=.78;ctx.filter="blur(26px)";ctx.fillStyle="rgba(0,0,0,.96)";ctx.beginPath();ctx.ellipse(780,955,920,155,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(0,1050);ctx.scale(1,-.25);ctx.globalAlpha=.32;ctx.filter="blur(3px)";ctx.drawImage(img,x,y,tw,th);ctx.restore();ctx.drawImage(img,x,y,tw,th)}
function drawBar(ctx:any){const W=1600,y=Number(barY)||900,h=138;const bar=ctx.createLinearGradient(0,y,W,y);bar.addColorStop(0,"#210000");bar.addColorStop(.25,"#b30000");bar.addColorStop(.5,"#111");bar.addColorStop(.78,"#b30000");bar.addColorStop(1,"#210000");ctx.fillStyle=bar;ctx.fillRect(0,y,W,h);ctx.strokeStyle="rgba(255,255,255,.26)";ctx.lineWidth=3;ctx.strokeRect(0,y,W,h);ctx.font="900 78px Arial Black, Microsoft JhengHei";ctx.fillStyle="#fff";ctx.shadowColor="rgba(0,0,0,.95)";ctx.shadowBlur=9;ctx.fillText(carModel,60,y+92);ctx.shadowBlur=0;ctx.font="900 50px Arial Black";ctx.fillStyle="#fff";ctx.fillText("SOFU",66,y+188);ctx.font="700 22px Arial";ctx.fillText("Used Car Dealers",66,y+214)}
async function compose(bgUrl:string,subUrl:string){const c=canvasRef.current;if(!c)return;const W=1600,H=1200;c.width=W;c.height=H;const ctx=c.getContext("2d")!;const bg=await loadImage(bgUrl);ctx.drawImage(bg,0,0,W,H);const sh=ctx.createLinearGradient(0,0,0,360);sh.addColorStop(0,"rgba(0,0,0,.82)");sh.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=sh;ctx.fillRect(0,0,W,360);drawTop(ctx);drawPrice(ctx);const sub=await loadImage(subUrl);if(mode==="cutout"&&urls.cutout)drawCutout(ctx,sub);else drawPhoto(ctx,sub);drawBar(ctx);setStatus(mode==="cutout"&&urls.cutout?"v23 完成：去背主體模式。":"v23 完成：照片框模式，版面已固定不亂跑。")}
async function oneClick(){setLoading(true);try{const sub=await getSubjectOrSource();const bg=await generateBackground();await compose(bg,sub)}catch(e:any){setStatus("失敗："+(e?.message||"未知錯誤"))}finally{setLoading(false)}}
async function recompositeOnly(){if(!backgroundUrl||!cutoutUrl){setStatus("需要先生成一次。");return}await compose(backgroundUrl,cutoutUrl)}
async function checkApi(){try{const res=await fetch("/api/health");const d=await res.json();setStatus(`API 狀態：\nOPENAI_API_KEY：${d.openaiKey?"已設定":"未設定"}\nREMOVE_BG_API_KEY：${d.removeBgKey?"已設定":"未設定"}\n版本：${d.version}`)}catch{setStatus("API 檢查失敗")}}
function download(type:"png"|"jpg"){const c=canvasRef.current;if(!c)return;const a=document.createElement("a");a.href=type==="png"?c.toDataURL("image/png"):c.toDataURL("image/jpeg",.92);a.download=`${carModel.replaceAll(" ","_")}_SOFU.${type}`;a.click()}
return <main className="page"><div className="wrap"><div className="badge">SOFU AI Poster Generator Real v24 CTR Engine</div><h1 className="title">首福汽車 AI 商業海報網頁軟體</h1><p className="sub">v23 穩定排版：沒有去背 PNG 自動用照片框模式；有去背 PNG 才用主體 showroom 模式。</p><section className="grid"><div className="card"><h2 className="h">上傳素材</h2><div className="notice">你現在用原圖也能生成，版面不會亂。要更像參考圖，請上傳去背人車 PNG。</div><div className="uploadGrid">{uploadItems.map(item=><div key={item.key}><button className="upload" onClick={()=>inputRefs.current[item.key]?.click()}>{urls[item.key]?<img src={urls[item.key]} alt={item.label}/>:<span>{item.label}{item.required?" *":""}</span>}</button><input hidden ref={el=>{inputRefs.current[item.key]=el}} type="file" accept="image/*" onChange={e=>pick(item.key,e.target.files?.[0])}/></div>)}</div><h2 className="h" style={{marginTop:18}}>文字內容</h2><Field label="車款" value={carModel} setValue={setCarModel}/><Field label="金屬大字" value={headline} setValue={setHeadline}/><Field label="左上日文" value={jpText} setValue={setJpText}/><Field label="白色資訊條" value={feature} setValue={setFeature}/><Field label="價格" value={price} setValue={setPrice}/><h2 className="h" style={{marginTop:18}}>排版模式</h2><label className="field"><span>模式</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="photo">照片框穩定模式</option><option value="cutout">去背主體模式</option></select></label><Check label="離線背景" value={useLocalBg} setValue={setUseLocalBg}/><Field label="照片Y" value={photoY} setValue={setPhotoY}/><Field label="照片高度" value={photoH} setValue={setPhotoH}/><Field label="底部紅條Y" value={barY} setValue={setBarY}/><Field label="價格牌X" value={priceX} setValue={setPriceX}/><Field label="價格牌Y" value={priceY} setValue={setPriceY}/><Field label="人車X" value={subjectX} setValue={setSubjectX}/><Field label="人車Y" value={subjectY} setValue={setSubjectY}/><Field label="人車寬度" value={subjectW} setValue={setSubjectW}/><button className="btn2" onClick={checkApi}>檢查 API 狀態</button><button className="btn" onClick={oneClick} disabled={loading}>{loading?"生成中...":"一鍵生成海報"}</button><button className="btn2" onClick={recompositeOnly}>只重新合成位置</button><button className="btn2" onClick={()=>download("png")}>下載 PNG 高畫質</button><button className="btn2" onClick={()=>download("jpg")}>下載 JPG 投放版</button></div><div className="card"><h2 className="h">4:3 海報輸出</h2><div className="canvasWrap"><canvas ref={canvasRef} width={1600} height={1200}/></div><div className="status">{status}</div><div className="preview"><Box title="主體 / 照片" url={cutoutUrl}/><Box title="背景" url={backgroundUrl}/></div><p className="small">v23 重點：先讓排版穩定。沒有去背圖不再硬套去背模式。</p></div></section></div></main>}
function Field({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>setValue(e.target.value)}/></label>}
function Check({label,value,setValue}:{label:string;value:boolean;setValue:(v:boolean)=>void}){return <label className="field"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>setValue(e.target.checked)}/></label>}
function Box({title,url}:{title:string;url?:string}){return <div className="box"><div className="boxTitle">{title}</div><div className="boxImg">{url?<img src={url} alt={title}/>:"尚未產生"}</div></div>}
